In [1]:
import numpy as np

In [2]:
# help(np)

# Array Creation

In [3]:
a = np.array([1,2,3,4,5,6, 2.3, "hello"])

In [4]:
a

array(['1', '2', '3', '4', '5', '6', '2.3', 'hello'], dtype='<U32')

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(8,)

In [7]:
a = np.array([[1,2,3], [1,4,5]])

In [8]:
a

array([[1, 2, 3],
       [1, 4, 5]])

In [9]:
a.shape

(2, 3)

In [10]:
a.reshape(3,2)

array([[1, 2],
       [3, 1],
       [4, 5]])

In [11]:
a.reshape(5,6)

ValueError: cannot reshape array of size 6 into shape (5,6)

In [12]:
# tuple of shape
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,3), dtype=np.int8)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int8)

In [14]:
# numpy functions

In [15]:
a = np.array([2,5,6,2,3,4,6,1,3,6,7])

In [16]:
a.max()

7

In [17]:
a.min()

1

In [18]:
a.sum()

45

In [19]:
a.mean()

4.090909090909091

In [20]:
a.shape

(11,)

In [21]:
a.sort()

In [22]:
a

array([1, 2, 2, 3, 3, 4, 5, 6, 6, 6, 7])

In [23]:
a = np.array([2,5,6,2,3,4,6,1,3,6,7])

In [24]:
a

array([2, 5, 6, 2, 3, 4, 6, 1, 3, 6, 7])

In [25]:
a.argmax()

10

In [26]:
a.argmin()

7

In [27]:
a.argsort()

array([ 7,  0,  3,  4,  8,  5,  1,  2,  6,  9, 10], dtype=int64)

In [28]:
a

array([2, 5, 6, 2, 3, 4, 6, 1, 3, 6, 7])

In [30]:
np.random.random()

0.01681359319033371

In [31]:
np.random.random(5)

array([0.9161528 , 0.21867315, 0.56017349, 0.91657726, 0.64945811])

In [32]:
np.random.random((5,5))

array([[0.42615349, 0.77739231, 0.21210807, 0.88268479, 0.28707458],
       [0.5113652 , 0.06321706, 0.09337392, 0.38426847, 0.09386837],
       [0.71261901, 0.13141431, 0.41750457, 0.24608156, 0.93106087],
       [0.08098884, 0.3318601 , 0.66199721, 0.95401315, 0.29276075],
       [0.30797979, 0.3285296 , 0.94566153, 0.61146055, 0.94709127]])

In [33]:
np.random.randint(1,50)

41

In [34]:
np.random.randint(1,50,10)

array([40, 38,  7, 26, 17, 44,  3, 26, 10,  2])

In [35]:
np.random.randint(1,50,(4,6))

array([[41,  7, 37, 20, 16, 18],
       [ 1, 35, 42, 12, 41,  3],
       [24,  6,  1, 45, 17, 49],
       [ 8, 31, 49, 13, 43, 30]])

In [36]:
x = np.random.randint(1,50,10)

In [37]:
x

array([15,  9, 17, 48, 40, 44, 10,  6, 40, 33])

In [38]:
x[0]

15

In [39]:
x[:5]

array([15,  9, 17, 48, 40])

In [40]:
x = np.random.randint(1,50,(4,6))

In [41]:
x

array([[23, 23,  5, 44,  9, 47],
       [28,  5,  3,  6, 30, 34],
       [36, 30, 36,  7,  3, 23],
       [23, 12, 48, 24, 13,  2]])

In [42]:
x[0]

array([23, 23,  5, 44,  9, 47])

In [43]:
x[1]

array([28,  5,  3,  6, 30, 34])

In [44]:
x[0:4]

array([[23, 23,  5, 44,  9, 47],
       [28,  5,  3,  6, 30, 34],
       [36, 30, 36,  7,  3, 23],
       [23, 12, 48, 24, 13,  2]])

In [45]:
x[:,0]

array([23, 28, 36, 23])

In [46]:
x[:, 0:3]

array([[23, 23,  5],
       [28,  5,  3],
       [36, 30, 36],
       [23, 12, 48]])

In [47]:
x

array([[23, 23,  5, 44,  9, 47],
       [28,  5,  3,  6, 30, 34],
       [36, 30, 36,  7,  3, 23],
       [23, 12, 48, 24, 13,  2]])

In [48]:
np.sum(x)

514

In [49]:
# row wise sum
np.sum(x, axis=1)

array([151, 106, 135, 122])

In [50]:
# col wise sum
np.sum(x, axis=0)

array([110,  70,  92,  81,  55, 106])

In [51]:
# col wise sum
np.sum(x, axis=0, keepdims=True)

array([[110,  70,  92,  81,  55, 106]])

In [52]:
np.hstack((x, np.array([[3],[12],[16],[5]])))

array([[23, 23,  5, 44,  9, 47,  3],
       [28,  5,  3,  6, 30, 34, 12],
       [36, 30, 36,  7,  3, 23, 16],
       [23, 12, 48, 24, 13,  2,  5]])

In [53]:
np.c_[x, np.array([[3],[12],[16],[5]])]

array([[23, 23,  5, 44,  9, 47,  3],
       [28,  5,  3,  6, 30, 34, 12],
       [36, 30, 36,  7,  3, 23, 16],
       [23, 12, 48, 24, 13,  2,  5]])

In [54]:
np.vstack((x, np.array([[2,4,7,3,6,23]])))

array([[23, 23,  5, 44,  9, 47],
       [28,  5,  3,  6, 30, 34],
       [36, 30, 36,  7,  3, 23],
       [23, 12, 48, 24, 13,  2],
       [ 2,  4,  7,  3,  6, 23]])

In [56]:
np.r_[x, np.array([[2,4,7,3,6,23]])]

array([[23, 23,  5, 44,  9, 47],
       [28,  5,  3,  6, 30, 34],
       [36, 30, 36,  7,  3, 23],
       [23, 12, 48, 24, 13,  2],
       [ 2,  4,  7,  3,  6, 23]])

In [57]:
#broadcasting

In [58]:
x

array([[23, 23,  5, 44,  9, 47],
       [28,  5,  3,  6, 30, 34],
       [36, 30, 36,  7,  3, 23],
       [23, 12, 48, 24, 13,  2]])

In [59]:
x + 1

array([[24, 24,  6, 45, 10, 48],
       [29,  6,  4,  7, 31, 35],
       [37, 31, 37,  8,  4, 24],
       [24, 13, 49, 25, 14,  3]])

In [60]:
x * 10

array([[230, 230,  50, 440,  90, 470],
       [280,  50,  30,  60, 300, 340],
       [360, 300, 360,  70,  30, 230],
       [230, 120, 480, 240, 130,  20]])

In [61]:
np.random.random(5)

array([0.18285012, 0.70334101, 0.50630844, 0.87989513, 0.18631245])

In [62]:
np.random.random(5)

array([0.23980108, 0.4425513 , 0.21387813, 0.85769343, 0.30472328])

In [74]:
np.random.seed(2)
x = np.random.random(5)

In [75]:
x

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])